name: Test flatpak build
on: [push, pull_request]

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: srb2kart-${{ matrix.arch }}.flatpak
          manifest-path: org.srb2.SRB2Kart.yml
          cache: true
          arch: ${{ matrix.arch }}
